In [1]:
import sys, os, time
%load_ext autoreload
%autoreload 2
%matplotlib inline
#%matplotlib tk
import numpy as np
import json
import matplotlib.pyplot as plt
from collections import namedtuple, OrderedDict
import random
from string import Formatter
from itertools import chain, product
# import gsm
from gsm import Savable
from gsm import tdict, tlist, tset
from gsm import Named, GameObject, GameLogger
from gsm import Array
from examples.tictactoe import TicTacToe

In [2]:
x = np.random.randn(3)
x

array([-0.34398902, -0.84450839, -1.56259909])

In [3]:
# Savable._Savable__subclasses.keys()

In [4]:
a = Array(np.zeros(3))
a

__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_ipython_display_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_mimebundle_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
__wrapped__
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_html_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_markdown_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_svg_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_png_
__class__
callable <class 'numpy.ndarray'>
__class__
c

array([ 0.,  0.,  0.])

In [5]:
type(a)

gsm.wrappers.Array

In [6]:
b = a+1
b, type(b)

(array([ 1.,  1.,  1.]), numpy.ndarray)

In [11]:
type(a.__add__(1))

__add__
callable <method-wrapper '__add__' of Array object at 0x7fb2fa938088>


numpy.ndarray

In [12]:
type(a.__add__)

__add__
callable <method-wrapper '__add__' of Array object at 0x7fb2fa938088>


method-wrapper

In [7]:
type(a.__wrapped__)

__wrapped__


numpy.ndarray

In [5]:
dir(np.ndarray)

[autoreload of gsm.wrappers failed: Traceback (most recent call last):
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 246, in check
    superreload(m, reload, self.old_objects)
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 369, in superreload
    module = reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/anwan/OneDrive - UW Office 365/Khan/Other/gsm/git/gsm/wrappers.py", line 10, in <module>
    class ObjectWrapper(ObjectProxy, Transactionable, Savable):
  File "

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [19]:
from wrapt import ObjectProxy
import numpy as np

class A(ObjectProxy):
    
    def __init__(self, a):
        super().__init__(a)
        
    def __save(self):
        print('saved')
        
    
    def __load(self, a):
        
        super().__init__(a)
        print('load')
        
    def __repr__(self):
        return self.__wrapped__.__repr__()
    
    @staticmethod
    def loadx(obj, data):
        obj.__init__(data)
    
    def __getattribute__(self, item):
        print(item)
        return super().__getattribute__(item)

In [20]:
a = A(np.zeros(10))
a

__class__
__class__
_ipython_canary_method_should_not_exist_
_ipython_display_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_mimebundle_
__class__
__class__
__wrapped__
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_html_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_markdown_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_svg_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_png_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_pdf_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_jpeg_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_latex_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_json_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_javascript_


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [18]:
b = A.__new__(A)
b.load(np.zeros(10))
b

__load


ValueError: wrapper has not been initialized

In [7]:
a += 1
type(a)

__main__.A

In [8]:
a.__wrapped__

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [3]:
x = tdict()
x

tdict()

In [3]:
p = Savable.create('gsm.util.Player')
p.x = 'x'
p.x

'x'

In [4]:
p

Player([('x', 'x')])

In [5]:
class Test(object):
    
    __m = 'm'
    
    def __new__(cls, *args, **kwargs):
        print(args, kwargs)
        return super().__new__(cls)
    
    def __init__(self, x):
        self.__x = x
        self.__dict__['__y'] = x+1
        
    def f(self):
        print(self.__x)
        print(self.__y)
        
    def __setattr__(self, x, y):
        print(x, y)
        super().__setattr__(x,y)
        
class T2(Test):
    def f(self, x):
        print(self, x)
    
    def g(self, x):
        print(x)

In [6]:
dir(t)

NameError: name 't' is not defined

In [7]:
t = Test(1)

(1,) {}
_Test__x 1


In [1]:
import time

In [5]:
time.strftime('%Y-%m-%d_%H%M%S')

'2019-09-17_135729'

In [9]:
Test._Test__m

'm'

In [27]:
t.__dict__

{'_Test__x': 1, '__y': 2}

In [29]:
t.__y

2

In [28]:
t.f()

1


AttributeError: 'Test' object has no attribute '_Test__y'

In [13]:
# class Sup(object):
#     @classmethod 
#     def makeit(cls):
#         self = cls.__new__(cls)
#         # etc etc, then
#         return self

class Test(object):
    
    def __init__(self, x):
        super().__init__()
        print(x)
        self.x = x
    
    def f(self):
        print(self.x)

In [14]:
a = Test()

TypeError: __init__() missing 1 required positional argument: 'x'

In [15]:
a = Test.__new__(Test)
a.f()

AttributeError: 'Test' object has no attribute 'x'

In [10]:
m = np.zeros((3,3), dtype=int)
m[0,0]= 1
m[1,1] = -1
m

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  0]])

In [11]:
json.loads(json.dumps({'x':1.245}))

{'x': 1.245}

In [6]:
np.array([1,2]).__getstate__()

AttributeError: 'numpy.ndarray' object has no attribute '__getstate__'

In [2]:
int('a')

ValueError: invalid literal for int() with base 10: 'a'

In [13]:
Test()

TypeError: __init__() missing 1 required positional argument: 'x'

In [12]:
x, y = np.mgrid[0:m.shape[0],0:m.shape[1]]

In [1]:
class Test(object):
    
    def __init__(self, x):
        print('init', x)
    
    def __init_subclass__(cls, **kwargs):
        print(cls)
        print(kwargs)
    
    def __new__(self, x):
        print('new', x)
        super().__new__(self)

In [6]:
Test(1)

new 1


In [2]:
class T2(object):
    pass

class T1(Test, T2):
    def __init__(self, x):
        super().__init__(x)
        print(x+1)

<class '__main__.T1'>
{}


In [ ]:
'test'.__getstate__()

In [4]:
type('a')(1)

[autoreload of gsm.core.actions failed: Traceback (most recent call last):
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 246, in check
    superreload(m, reload, self.old_objects)
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 369, in superreload
    module = reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/anwan/One

'1'

In [13]:
s = 'test {} {{a {:3.2f} b {:} c {p[x]:} d'
s.format('A', 1234.2351, 'B', p={'x':'X'})

'test A {a 1234.24 b B c X d'

In [14]:
F = Formatter()
list(F.parse(s))

[('test ', '', '', None),
 (' {', None, None, None),
 ('a ', '', '3.2f', None),
 (' b ', '', '', None),
 (' c ', 'p[x]', '', None),
 (' d', None, None, None)]

In [15]:
'test'.__class__.__name__

'str'

In [2]:
class Parent:
    def signal(self):
        print('bing')

In [3]:
a = tdict(a=10, c='hello', _tracker=Parent())
a._tracker = Parent()
a

tdict('a':10, 'c':'hello')

In [4]:
a.begin()

In [5]:
a.a = 11
a.b = tdict()
a.d = 'testing'
a.b.deep = 'yes'
a

bing
bing
bing
bing


tdict('a':11, 'c':'hello', 'b':tdict('deep':'yes'), 'd':'testing')

In [6]:
a.abort()
a

tdict('a':10, 'c':'hello')

In [7]:
a._tracker

In [7]:
a = tlist([tdict(x=1), tdict(ad=3)], _tracker=Parent())
a

bing


[tdict('x':1), tdict('ad':3)]

In [9]:
a.begin()
a.append('x')
a

bing


[tdict('x':1), tdict('ad':3), 'x']

In [10]:
# a.add(tdict())
for x in a:
#     print(x)
    try:
        x.v = 14
    except Exception as e:
        print('pass',x)
#         raise e
        pass
a

bing
bing
pass x


[tdict('x':1, 'v':14), tdict('ad':3, 'v':14), 'x']

In [12]:
a.abort()
a

[tdict('x':1), tdict('ad':3)]